import './screenCards.css'
function LogoText(){
    return(
        <div className='backdrop'>
            <div className="screenCard">
                <br />
                <p>Lorem ipsum dolor sit amet. Rem repellat cumque et molestiae corporis in velit quos. Est quas velit et alias tenetur non molestiae repudiandae. Ad nobis itaque aut illo laudantium in fugit aspernatur qui facere doloremque et adipisci rerum. Et obcaecati illum aut consequatur debitis est doloribus consequatur et enim impedit. Ex porro eaque qui ipsa enim et excepturi voluptatibus sed quaerat delectus eos quam placeat. A suscipit voluptate quo officiis doloribus ut veritatis nihil est quia voluptatem et molestias voluptate. Cum molestias suscipit 33 rerum laborum ut perferendis assumenda sed dolorum maxime. Qui vitae voluptas ut galisum animi qui repudiandae assumenda sit sunt eveniet qui tempora dolore ut officia illum id nobis perferendis. Est omnis omnis sed tempore atque ut sint deserunt a neque corrupti ut placeat quos quo facere sunt? Hic aliquam sunt ut enim iste qui officiis neque id dicta magni et reprehenderit maxime ut esse quae. Qui eveniet deserunt et aliquam earum et soluta aspernatur. Qui rerum voluptatem eos ipsa dolorum id assumenda repellendus. Aut dolorem voluptate ut architecto consequatur 33 voluptatem libero. Eum consequatur consequatur id odio voluptatem qui galisum facere in expedita atque. this text have no easter egg.</p>
                <p>Ex Quis velit est exercitationem rerum et iure eius non eaque maiores a doloremque iure ut quis dolorem. Quo explicabo nobis At incidunt voluptates id pariatur assumenda et dolores quod. Sed molestias fugiat et voluptatem voluptatum aut reiciendis sunt eos molestias repudiandae et tempora possimus vel fugiat reprehenderit. Ut quisquam labore nam deleniti optio est exercitationem consequuntur et sapiente aliquid et animi magni! Ex doloribus possimus sed fugit odio sit suscipit voluptates qui laborum consequatur et doloribus ipsum. Sit adipisci rerum est architecto quisquam et quod quam non nisi neque aut facere soluta qui obcaecati dolorum. Et culpa odit et rerum delectus ut nostrum voluptas? Qui velit expedita sed perspiciatis nesciunt aut iusto dolor eos suscipit commodi qui voluptas soluta in quae sunt sit voluptatem autem! Eum deleniti suscipit nam suscipit corporis est ullam porro. Et obcaecati omnis et architecto dicta quo reiciendis rerum. In iure perferendis et reiciendis aspernatur aut quisquam fuga? Ut sunt veniam sed quam esse sit eius aliquam et commodi obcaecati. Sit pariatur obcaecati vel voluptate iste ex architecto minus id possimus eligendi non nihil ratione qui similique impedit. Nam inventore doloribus ut assumenda quae ut . </p>
                <p>Nam facilis quaerat et animi reiciendis ut distinctio labore rem voluptas galisum et voluptas enim. Et nemo eius id quidem quibusdam id totam incidunt. Et sint Quis et delectus nihil aut sunt nemo! Sit aspernatur aperiam sit officia voluptatem qui esse neque non amet fuga sed dolores obcaecati id iusto placeat. In reprehenderit quia sed quia iure ut nisi deserunt. Nam nihil reprehenderit et consequatur repudiandae quo veniam quia eum pariatur omnis. Sed dignissimos illo in obcaecati galisum et excepturi veritatis ut recusandae mollitia eum nemo omnis. Et nemo atque et dolorem debitis ad voluptatem sunt rem eligendi quae non voluptatem dolorem sit cupiditate veniam et minima ipsa. Sit culpa excepturi ad libero tempora nam fugit dolor. At velit rerum et officiis ipsum eos Quis autem! In quaerat nisi rem maxime laudantium id veritatis consequatur vel autem eligendi eos exercitationem beatae et odio nostrum ut nulla architecto. Quo voluptatum voluptas est voluptatem aliquam non officia tenetur. Qui laborum deserunt ut iure eveniet qui deleniti voluptatem. Quo fuga error ut ratione doloribus et recusandae labore eum eius incidunt sit aperiam odio. Et vero consequuntur cum praesentium facilis et impedit culpa aut iusto harum. Est harum consequatur? </p>
                <h2 id='middleText'>BRING DESIGN AND IMAGINATION TO LIFE</h2>
                <p>Lorem ipsum dolor sit amet. Rem repellat cumque et molestiae corporis in velit quos. Est quas velit et alias tenetur non molestiae repudiandae. Ad nobis itaque aut illo laudantium in fugit aspernatur qui facere doloremque et adipisci rerum. Et obcaecati illum aut consequatur debitis est doloribus consequatur et enim impedit. Ex porro eaque qui ipsa enim et excepturi voluptatibus sed quaerat delectus eos quam placeat. A suscipit voluptate quo officiis doloribus ut veritatis nihil est quia voluptatem et molestias voluptate. Cum molestias suscipit 33 rerum laborum ut perferendis assumenda sed dolorum maxime. Qui vitae voluptas ut galisum animi qui repudiandae assumenda sit sunt eveniet qui tempora dolore ut officia illum id nobis perferendis. Est omnis omnis sed tempore atque ut sint deserunt a neque corrupti ut placeat quos quo facere sunt? Hic aliquam sunt ut enim iste qui officiis neque id dicta magni et reprehenderit maxime ut esse quae. Qui eveniet deserunt et aliquam earum et soluta aspernatur. Qui rerum voluptatem eos ipsa dolorum id assumenda repellendus. Aut dolorem voluptate ut architecto consequatur 33 voluptatem libero. Eum consequatur consequatur id odio voluptatem qui galisum facere in expedita atque. this text have no easter egg.</p>
                <p>Ex Quis velit est exercitationem rerum et iure eius non eaque maiores a doloremque iure ut quis dolorem. Quo explicabo nobis At incidunt voluptates id pariatur assumenda et dolores quod. Sed molestias fugiat et voluptatem voluptatum aut reiciendis sunt eos molestias repudiandae et tempora possimus vel fugiat reprehenderit. Ut quisquam labore nam deleniti optio est exercitationem consequuntur et sapiente aliquid et animi magni! Ex doloribus possimus sed fugit odio sit suscipit voluptates qui laborum consequatur et doloribus ipsum. Sit adipisci rerum est architecto quisquam et quod quam non nisi neque aut facere soluta qui obcaecati dolorum. Et culpa odit et rerum delectus ut nostrum voluptas? Qui velit expedita sed perspiciatis nesciunt aut iusto dolor eos suscipit commodi qui voluptas soluta in quae sunt sit voluptatem autem! Eum deleniti suscipit nam suscipit corporis est ullam porro. Et obcaecati omnis et architecto dicta quo reiciendis rerum. In iure perferendis et reiciendis aspernatur aut quisquam fuga? Ut sunt veniam sed quam esse sit eius aliquam et commodi obcaecati. Sit pariatur obcaecati vel voluptate iste ex architecto minus id possimus eligendi non nihil ratione qui similique impedit. Nam inventore doloribus ut assumenda quae ut . </p>
                <p>Nam facilis quaerat et animi reiciendis ut distinctio labore rem voluptas galisum et voluptas enim. Et nemo eius id quidem quibusdam id totam incidunt. Et sint Quis et delectus nihil aut sunt nemo! Sit aspernatur aperiam sit officia voluptatem qui esse neque non amet fuga sed dolores obcaecati id iusto placeat. In reprehenderit quia sed quia iure ut nisi deserunt. Nam nihil reprehenderit et consequatur repudiandae quo veniam quia eum pariatur omnis. Sed dignissimos illo in obcaecati galisum et excepturi veritatis ut recusandae mollitia eum nemo omnis. Et nemo atque et dolorem debitis ad voluptatem sunt rem eligendi quae non voluptatem dolorem sit cupiditate veniam et minima ipsa. Sit culpa excepturi ad libero tempora nam fugit dolor. At velit rerum et officiis ipsum eos Quis autem! In quaerat nisi rem maxime laudantium id veritatis consequatur vel autem eligendi eos exercitationem beatae et odio nostrum ut nulla architecto. Quo voluptatum voluptas est voluptatem aliquam non officia tenetur. Qui laborum deserunt ut <span id='down'>scroll down to begin</span> voluptatem. Quo fuga error ut ratione doloribus et recusandae labore eum eius incidunt sit aperiam odio. Et vero consequuntur cum praesentium facilis et impedit culpa aut iusto and that's it. </p>
            </div>
        </div>
    )
}

export default LogoText